import { 
  Organization, 
  Supplier, 
  ContractItem, 
  DocumentItem, 
  SavingsOpportunity, 
  SpendRecord, 
  MarketBenchmark,
  Profile
} from './types';

export const DEMO_USER: Profile = {
  id: 'usr_nova_01',
  email: 'andrei.popescu@novaretail.ro',
  fullName: 'Andrei Popescu',
  phone: '+40 722 123 456',
  role: 'Director Financiar (CFO)',
  createdAt: '2025-01-15T09:00:00Z',
};

export const DEMO_ORG: Organization = {
  id: 'org_nova_retail_001',
  name: 'Nova Retail SRL',
  cui: 'RO 38491024',
  registrationNumber: 'J40/12930/2018',
  industry: 'Retail & Distribuție Bunuri de Consum',
  employeeRange: '25-50 angajați',
  monthlyOpexRon: 35700,
  saveScore: 74,
  isDemo: true,
  currency: 'RON',
  createdAt: '2025-01-15T09:30:00Z',
};

export const DEMO_SUPPLIERS: Supplier[] = [
  {
    id: 'sup_vodafone',
    organizationId: DEMO_ORG.id,
    name: 'Vodafone România SA',
    cui: 'RO 8970105',
    category: 'Telecom',
    contactEmail: 'corporate@vodafone.ro',
    rating: 4.2,
    isPreferred: false,
    totalAnnualSpendRon: 18400,
    contractCount: 1,
    invoiceCount: 3,
    createdAt: '2025-01-16T10:00:00Z',
  },
  {
    id: 'sup_google',
    organizationId: DEMO_ORG.id,
    name: 'Google Ireland Ltd (Workspace & Cloud)',
    cui: 'IE 6388047V',
    category: 'Software',
    contactEmail: 'billing-support@google.com',
    rating: 4.8,
    isPreferred: true,
    totalAnnualSpendRon: 26400,
    contractCount: 1,
    invoiceCount: 2,
    createdAt: '2025-01-16T10:00:00Z',
  },
  {
    id: 'sup_dpd',
    organizationId: DEMO_ORG.id,
    name: 'DPD România (Dynamic Parcel Distribution SA)',
    cui: 'RO 17563040',
    category: 'Curierat',
    contactEmail: 'sales.b2b@dpd.ro',
    rating: 3.9,
    isPreferred: false,
    totalAnnualSpendRon: 94200,
    contractCount: 1,
    invoiceCount: 3,
    createdAt: '2025-01-16T10:00:00Z',
  },
  {
    id: 'sup_lyreco',
    organizationId: DEMO_ORG.id,
    name: 'Lyreco România SRL',
    cui: 'RO 18940210',
    category: 'Consumabile',
    contactEmail: 'orders@lyreco.ro',
    rating: 4.5,
    isPreferred: true,
    totalAnnualSpendRon: 34500,
    contractCount: 0,
    invoiceCount: 2,
    createdAt: '2025-01-16T10:00:00Z',
  },
  {
    id: 'sup_eon',
    organizationId: DEMO_ORG.id,
    name: 'E.ON Energie România SA',
    cui: 'RO 22043010',
    category: 'Energie',
    contactEmail: 'business@eon-energie.ro',
    rating: 3.6,
    isPreferred: false,
    totalAnnualSpendRon: 182000,
    contractCount: 1,
    invoiceCount: 1,
    createdAt: '2025-01-16T10:00:00Z',
  },
  {
    id: 'sup_contaudit',
    organizationId: DEMO_ORG.id,
    name: 'ContAudit & Tax Advisory SRL',
    cui: 'RO 29401928',
    category: 'Servicii',
    contactEmail: 'office@contaudit-expert.ro',
    rating: 4.9,
    isPreferred: true,
    totalAnnualSpendRon: 73000,
    contractCount: 1,
    invoiceCount: 1,
    createdAt: '2025-01-16T10:00:00Z',
  },
];

// Helper to compute dynamic dates relative to current date (2026-08-31)
export const DEMO_CONTRACTS: ContractItem[] = [
  {
    id: 'ctr_vdf_01',
    organizationId: DEMO_ORG.id,
    supplierId: 'sup_vodafone',
    supplierName: 'Vodafone România SA',
    title: 'Abonament Flotă Voce & Date Mobile (24 SIM)',
    category: 'Telecom',
    annualValue: 18400,
    currency: 'RON',
    startDate: '2024-09-28',
    expiryDate: '2026-09-28', // Expiring in 28 days!
    noticePeriodDays: 30,
    noticeDeadline: '2026-08-29', // In renewal notice window!
    automaticRenewal: true,
    status: 'in_renewal_window',
    paymentTerms: '15 zile de la emitere',
    daysUntilExpiry: 28,
    daysUntilNotice: -2,
    notes: 'Clauză de tacită prelungire pe 12 luni adiționale dacă nu se trimite notificare cu 30 de zile înainte.',
    createdAt: '2025-01-16T11:00:00Z',
  },
  {
    id: 'ctr_eon_01',
    organizationId: DEMO_ORG.id,
    supplierId: 'sup_eon',
    supplierName: 'E.ON Energie România SA',
    title: 'Contract Furnizare Energie Electrică Non-Casnic (Puncte Consum Depozit)',
    category: 'Energie',
    annualValue: 182000,
    currency: 'RON',
    startDate: '2025-10-25',
    expiryDate: '2026-10-25', // Expiring in 55 days!
    noticePeriodDays: 45,
    noticeDeadline: '2026-09-10', // Notice deadline in 10 days!
    automaticRenewal: true,
    status: 'in_renewal_window',
    paymentTerms: '30 zile net',
    daysUntilExpiry: 55,
    daysUntilNotice: 10,
    notes: 'Indexare automată cu prețul OPCOM dacă nu se acceptă oferta de prelungire.',
    createdAt: '2025-01-16T11:00:00Z',
  },
  {
    id: 'ctr_dpd_01',
    organizationId: DEMO_ORG.id,
    supplierId: 'sup_dpd',
    supplierName: 'DPD România (Dynamic Parcel Distribution SA)',
    title: 'Contract Cadru Servicii Naționale Curierat E-commerce',
    category: 'Curierat',
    annualValue: 94200,
    currency: 'RON',
    startDate: '2025-12-01',
    expiryDate: '2026-12-01', // 92 days
    noticePeriodDays: 30,
    noticeDeadline: '2026-11-01',
    automaticRenewal: true,
    status: 'active',
    paymentTerms: 'Săptămânal / 7 zile',
    daysUntilExpiry: 92,
    daysUntilNotice: 62,
    notes: 'Suprataxă de combustibil fluctuantă + indexare index volum.',
    createdAt: '2025-01-16T11:00:00Z',
  },
  {
    id: 'ctr_gsuite_01',
    organizationId: DEMO_ORG.id,
    supplierId: 'sup_google',
    supplierName: 'Google Ireland Ltd',
    title: 'Google Workspace Enterprise Plan (32 User Seats)',
    category: 'Software',
    annualValue: 26400,
    currency: 'RON',
    startDate: '2026-03-01',
    expiryDate: '2027-03-01',
    noticePeriodDays: 0,
    noticeDeadline: '2027-03-01',
    automaticRenewal: true,
    status: 'active',
    paymentTerms: 'Card bancar automat (Lunar)',
    daysUntilExpiry: 182,
    daysUntilNotice: 182,
    notes: 'Facturat direct în USD/EUR convertit la cursul BNR + 1.5%.',
    createdAt: '2025-01-16T11:00:00Z',
  },
  {
    id: 'ctr_conta_01',
    organizationId: DEMO_ORG.id,
    supplierId: 'sup_contaudit',
    supplierName: 'ContAudit & Tax Advisory SRL',
    title: 'Contract Prestări Servicii Contabilitate, Salarizare și Expertiză Fiscală',
    category: 'Servicii',
    annualValue: 73000,
    currency: 'RON',
    startDate: '2026-01-01',
    expiryDate: '2026-12-31',
    noticePeriodDays: 60,
    noticeDeadline: '2026-10-31',
    automaticRenewal: true,
    status: 'active',
    paymentTerms: '30 zile net de la sfârșitul lunii',
    daysUntilExpiry: 122,
    daysUntilNotice: 61,
    notes: 'Tarif fix lunar 6.083 lei + ore suplimentare audit inventar.',
    createdAt: '2025-01-16T11:00:00Z',
  },
];

export const DEMO_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc_vdf_inv_08',
    organizationId: DEMO_ORG.id,
    supplierId: 'sup_vodafone',
    supplierName: 'Vodafone România SA',
    fileName: 'Factura_VDF_RO892301_Aug2026.pdf',
    filePath: 'org_nova_retail_001/invoices/Factura_VDF_RO892301_Aug2026.pdf',
    fileSizeBytes: 245000,
    mimeType: 'application/pdf',
    documentType: 'invoice',
    status: 'extracted',
    uploadedByName: 'Andrei Popescu',
    createdAt: '2026-08-15T08:30:00Z',
    extraction: {
      id: 'ext_vdf_08',
      documentId: 'doc_vdf_inv_08',
      organizationId: DEMO_ORG.id,
      supplier: 'Vodafone România SA',
      documentType: 'invoice',
      category: 'Telecom',
      invoiceNumber: 'VF-89230182',
      invoiceDate: '2026-08-10',
      dueDate: '2026-08-25',
      invoiceTotal: 1533.33,
      currency: 'RON',
      billingPeriod: '01.07.2026 - 31.07.2026',
      unitPrice: 63.88,
      quantity: 24,
      automaticRenewal: true,
      confidence: 96,
      needsReview: false,
      createdAt: '2026-08-15T08:31:00Z',
    },
  },
  {
    id: 'doc_vdf_ctr_01',
    organizationId: DEMO_ORG.id,
    supplierId: 'sup_vodafone',
    supplierName: 'Vodafone România SA',
    fileName: 'Contract_Cadru_Vodafone_Corp_2024.pdf',
    filePath: 'org_nova_retail_001/contracts/Contract_Cadru_Vodafone_Corp_2024.pdf',
    fileSizeBytes: 890000,
    mimeType: 'application/pdf',
    documentType: 'supplier_contract',
    status: 'verified',
    uploadedByName: 'Andrei Popescu',
    createdAt: '2026-08-10T14:15:00Z',
    extraction: {
      id: 'ext_vdf_ctr',
      documentId: 'doc_vdf_ctr_01',
      organizationId: DEMO_ORG.id,
      supplier: 'Vodafone România SA',
      documentType: 'supplier_contract',
      category: 'Telecom',
      invoiceTotal: 18400,
      currency: 'RON',
      contractStart: '2024-09-28',
      contractEnd: '2026-09-28',
      noticePeriodDays: 30,
      automaticRenewal: true,
      confidence: 92,
      needsReview: false,
      createdAt: '2026-08-10T14:16:00Z',
    },
  },
  {
    id: 'doc_dpd_inv_08',
    organizationId: DEMO_ORG.id,
    supplierId: 'sup_dpd',
    supplierName: 'DPD România',
    fileName: 'Factura_DPD_RO_6781290_Aug2026.pdf',
    filePath: 'org_nova_retail_001/invoices/Factura_DPD_RO_6781290_Aug2026.pdf',
    fileSizeBytes: 310000,
    mimeType: 'application/pdf',
    documentType: 'invoice',
    status: 'extracted',
    uploadedByName: 'Andrei Popescu',
    createdAt: '2026-08-18T11:20:00Z',
    extraction: {
      id: 'ext_dpd_08',
      documentId: 'doc_dpd_inv_08',
      organizationId: DEMO_ORG.id,
      supplier: 'DPD România (Dynamic Parcel Distribution SA)',
      documentType: 'invoice',
      category: 'Curierat',
      invoiceNumber: 'DPD-RO-6781290',
      invoiceDate: '2026-08-15',
      dueDate: '2026-08-22',
      invoiceTotal: 7850.00,
      currency: 'RON',
      billingPeriod: 'Iulie 2026 (612 expedieri)',
      quantity: 612,
      unitPrice: 12.82,
      automaticRenewal: true,
      confidence: 94,
      needsReview: false,
      createdAt: '2026-08-18T11:21:00Z',
    },
  },
  {
    id: 'doc_dpd_ctr_01',
    organizationId: DEMO_ORG.id,
    supplierId: 'sup_dpd',
    supplierName: 'DPD România',
    fileName: 'Contract_DPD_Curierat_2025.pdf',
    filePath: 'org_nova_retail_001/contracts/Contract_DPD_Curierat_2025.pdf',
    fileSizeBytes: 640000,
    mimeType: 'application/pdf',
    documentType: 'supplier_contract',
    status: 'verified',
    uploadedByName: 'Andrei Popescu',
    createdAt: '2026-08-10T14:20:00Z',
    extraction: {
      id: 'ext_dpd_ctr',
      documentId: 'doc_dpd_ctr_01',
      organizationId: DEMO_ORG.id,
      supplier: 'DPD România',
      documentType: 'supplier_contract',
      category: 'Curierat',
      invoiceTotal: 94200,
      currency: 'RON',
      contractStart: '2025-12-01',
      contractEnd: '2026-12-01',
      noticePeriodDays: 30,
      automaticRenewal: true,
      confidence: 91,
      needsReview: false,
      createdAt: '2026-08-10T14:21:00Z',
    },
  },
  {
    id: 'doc_google_inv_08',
    organizationId: DEMO_ORG.id,
    supplierId: 'sup_google',
    supplierName: 'Google Ireland Ltd',
    fileName: 'Google_Workspace_INV_AUG2026.pdf',
    filePath: 'org_nova_retail_001/invoices/Google_Workspace_INV_AUG2026.pdf',
    fileSizeBytes: 180000,
    mimeType: 'application/pdf',
    documentType: 'subscription_agreement',
    status: 'extracted',
    uploadedByName: 'Andrei Popescu',
    createdAt: '2026-08-02T07:10:00Z',
    extraction: {
      id: 'ext_google_08',
      documentId: 'doc_google_inv_08',
      organizationId: DEMO_ORG.id,
      supplier: 'Google Ireland Ltd',
      documentType: 'subscription_agreement',
      category: 'Software',
      invoiceNumber: 'GW-2026-98124',
      invoiceDate: '2026-08-01',
      dueDate: '2026-08-01',
      invoiceTotal: 2200.00,
      currency: 'RON',
      billingPeriod: '01.07.2026 - 31.07.2026 (32 Seats)',
      unitPrice: 68.75,
      quantity: 32,
      automaticRenewal: true,
      confidence: 98,
      needsReview: false,
      createdAt: '2026-08-02T07:11:00Z',
    },
  },
  {
    id: 'doc_lyreco_inv_07',
    organizationId: DEMO_ORG.id,
    supplierId: 'sup_lyreco',
    supplierName: 'Lyreco România SRL',
    fileName: 'Factura_Lyreco_Birotica_Iul2026.pdf',
    filePath: 'org_nova_retail_001/invoices/Factura_Lyreco_Birotica_Iul2026.pdf',
    fileSizeBytes: 420000,
    mimeType: 'application/pdf',
    documentType: 'invoice',
    status: 'requires_review', // Demonstrates low confidence manual review trigger!
    uploadedByName: 'Andrei Popescu',
    createdAt: '2026-08-20T16:45:00Z',
    extraction: {
      id: 'ext_lyreco_07',
      documentId: 'doc_lyreco_inv_07',
      organizationId: DEMO_ORG.id,
      supplier: 'Lyreco România SRL (scan neclar antet)',
      documentType: 'invoice',
      category: 'Consumabile',
      invoiceNumber: 'LYR-849102',
      invoiceDate: '2026-07-28',
      dueDate: '2026-08-28',
      invoiceTotal: 2875.50,
      currency: 'RON',
      billingPeriod: 'Iulie 2026',
      automaticRenewal: false,
      confidence: 76, // Below 85% -> flagged for user review!
      needsReview: true,
      reviewNotes: 'Calitatea scanării este medie. Confirmă manual totalul facturii și denumirea furnizorului.',
      fieldConfidences: {
        supplier: 80,
        invoiceTotal: 74,
        category: 95,
        invoiceDate: 78,
      },
      createdAt: '2026-08-20T16:46:00Z',
    },
  },
  {
    id: 'doc_eon_inv_07',
    organizationId: DEMO_ORG.id,
    supplierId: 'sup_eon',
    supplierName: 'E.ON Energie România SA',
    fileName: 'Factura_EON_Energie_Iul2026.pdf',
    filePath: 'org_nova_retail_001/invoices/Factura_EON_Energie_Iul2026.pdf',
    fileSizeBytes: 512000,
    mimeType: 'application/pdf',
    documentType: 'invoice',
    status: 'extracted',
    uploadedByName: 'Andrei Popescu',
    createdAt: '2026-08-05T12:00:00Z',
    extraction: {
      id: 'ext_eon_07',
      documentId: 'doc_eon_inv_07',
      organizationId: DEMO_ORG.id,
      supplier: 'E.ON Energie România SA',
      documentType: 'invoice',
      category: 'Energie',
      invoiceNumber: 'EON-10928374',
      invoiceDate: '2026-07-31',
      dueDate: '2026-08-30',
      invoiceTotal: 15166.66,
      currency: 'RON',
      billingPeriod: '01.07.2026 - 31.07.2026 (Consum 18.2 MWh)',
      quantity: 18.2,
      unitPrice: 833.33,
      automaticRenewal: true,
      confidence: 95,
      needsReview: false,
      createdAt: '2026-08-05T12:01:00Z',
    },
  },
  {
    id: 'doc_conta_inv_08',
    organizationId: DEMO_ORG.id,
    supplierId: 'sup_contaudit',
    supplierName: 'ContAudit & Tax Advisory SRL',
    fileName: 'Factura_ContAudit_Servicii_Aug2026.pdf',
    filePath: 'org_nova_retail_001/invoices/Factura_ContAudit_Servicii_Aug2026.pdf',
    fileSizeBytes: 210000,
    mimeType: 'application/pdf',
    documentType: 'invoice',
    status: 'extracted',
    uploadedByName: 'Andrei Popescu',
    createdAt: '2026-08-25T09:15:00Z',
    extraction: {
      id: 'ext_conta_08',
      documentId: 'doc_conta_inv_08',
      organizationId: DEMO_ORG.id,
      supplier: 'ContAudit & Tax Advisory SRL',
      documentType: 'invoice',
      category: 'Servicii',
      invoiceNumber: 'CTA-2026-0811',
      invoiceDate: '2026-08-25',
      dueDate: '2026-09-25',
      invoiceTotal: 6083.33,
      currency: 'RON',
      billingPeriod: 'August 2026',
      automaticRenewal: true,
      confidence: 99,
      needsReview: false,
      createdAt: '2026-08-25T09:16:00Z',
    },
  },
];

export const DEMO_SAVINGS_OPPORTUNITIES: SavingsOpportunity[] = [
  {
    id: 'opp_telecom_01',
    organizationId: DEMO_ORG.id,
    supplierId: 'sup_vodafone',
    supplierName: 'Vodafone România SA',
    contractId: 'ctr_vdf_01',
    title: 'Contract telecom flotă mobilă posibil supraevaluat',
    category: 'Telecom',
    currentAnnualCost: 18400,
    estimatedSavingsMin: 2800,
    estimatedSavingsMax: 4100,
    confidenceLevel: 'medium',
    provenance: 'dataset_source',
    benchmarkReference: 'B2B SME Telco Index Q2 2026 (eSIM/Voice pool)',
    reason: 'Costul tău mediu este de 64 lei/SIM/lună cu pachete supradimensionate de date. Mediana companiilor cu 20-50 angajați din România este 45-50 lei/SIM pentru același volum efectiv de trafic.',
    recommendedAction: 'Activează analiza SAVE pentru a renegocia pachetele înainte de expirarea contractului în 28 zile.',
    status: 'open',
    createdAt: '2026-08-20T10:00:00Z',
  },
  {
    id: 'opp_curierat_01',
    organizationId: DEMO_ORG.id,
    supplierId: 'sup_dpd',
    supplierName: 'DPD România (Dynamic Parcel Distribution SA)',
    contractId: 'ctr_dpd_01',
    title: 'Tarif curierat e-commerce nereglementat volumetric',
    category: 'Curierat',
    currentAnnualCost: 94200,
    estimatedSavingsMin: 12500,
    estimatedSavingsMax: 16800,
    confidenceLevel: 'high',
    provenance: 'manually_verified',
    benchmarkReference: 'Ofertă cotată parteneri SAVE B2B Logistics',
    reason: 'Compania ta expediază ~610 colete/lună la un cost mediu de 12.82 lei/colet. La acest prag de volum se califică pentru tarife negociate de 10.50–11.00 lei/colet standard + reducere taxa combustibil.',
    recommendedAction: 'Lansează cerere de optimizare SAVE pentru aplicarea grilei de volum B2B dedicate.',
    status: 'open',
    createdAt: '2026-08-21T11:30:00Z',
  },
  {
    id: 'opp_software_01',
    organizationId: DEMO_ORG.id,
    supplierId: 'sup_google',
    supplierName: 'Google Ireland Ltd (Workspace)',
    contractId: 'ctr_gsuite_01',
    title: 'Optimizare structură licențe Google Workspace',
    category: 'Software',
    currentAnnualCost: 26400,
    estimatedSavingsMin: 3600,
    estimatedSavingsMax: 5200,
    confidenceLevel: 'high',
    provenance: 'supplier_quote',
    benchmarkReference: 'Catalog oficial Google Cloud Reseller Partner',
    reason: 'Toate cele 32 de conturi sunt alocate pe Enterprise tier (68.75 lei/user/lună). Analiza rolurilor arată că 18 utilizatori folosesc doar email și drive basic, fiind eligibili pentru Business Starter/Standard.',
    recommendedAction: 'Ajustează mixul de licențiere prin partenerul SAVE Cloud fără întreruperea serviciilor.',
    status: 'open',
    createdAt: '2026-08-22T09:00:00Z',
  },
];

export const DEMO_SPEND_RECORDS: SpendRecord[] = [
  // Energie: ~15.166 lei/month
  { id: 'sp_eon_1', organizationId: DEMO_ORG.id, supplierId: 'sup_eon', supplierName: 'E.ON Energie România', category: 'Energie', description: 'Consum energie electrică & gaz depozit', amount: 15166.66, currency: 'RON', spendDate: '2026-08-01', isRecurring: true, periodType: 'monthly', createdAt: '2026-08-05T00:00:00Z' },
  { id: 'sp_eon_2', organizationId: DEMO_ORG.id, supplierId: 'sup_eon', supplierName: 'E.ON Energie România', category: 'Energie', description: 'Consum energie electrică & gaz depozit', amount: 14850.00, currency: 'RON', spendDate: '2026-07-01', isRecurring: true, periodType: 'monthly', createdAt: '2026-07-05T00:00:00Z' },
  { id: 'sp_eon_3', organizationId: DEMO_ORG.id, supplierId: 'sup_eon', supplierName: 'E.ON Energie România', category: 'Energie', description: 'Consum energie electrică & gaz depozit', amount: 15300.00, currency: 'RON', spendDate: '2026-06-01', isRecurring: true, periodType: 'monthly', createdAt: '2026-06-05T00:00:00Z' },

  // Curierat: ~7.850 lei/month
  { id: 'sp_dpd_1', organizationId: DEMO_ORG.id, supplierId: 'sup_dpd', supplierName: 'DPD România', category: 'Curierat', description: 'Servicii livrare colete comenzi magazin online', amount: 7850.00, currency: 'RON', spendDate: '2026-08-01', isRecurring: true, periodType: 'monthly', createdAt: '2026-08-18T00:00:00Z' },
  { id: 'sp_dpd_2', organizationId: DEMO_ORG.id, supplierId: 'sup_dpd', supplierName: 'DPD România', category: 'Curierat', description: 'Servicii livrare colete comenzi magazin online', amount: 7620.00, currency: 'RON', spendDate: '2026-07-01', isRecurring: true, periodType: 'monthly', createdAt: '2026-07-18T00:00:00Z' },
  { id: 'sp_dpd_3', organizationId: DEMO_ORG.id, supplierId: 'sup_dpd', supplierName: 'DPD România', category: 'Curierat', description: 'Servicii livrare colete comenzi magazin online', amount: 8100.00, currency: 'RON', spendDate: '2026-06-01', isRecurring: true, periodType: 'monthly', createdAt: '2026-06-18T00:00:00Z' },

  // Servicii Contabilitate: ~6.083 lei/month
  { id: 'sp_cnt_1', organizationId: DEMO_ORG.id, supplierId: 'sup_contaudit', supplierName: 'ContAudit & Tax Advisory', category: 'Servicii', description: 'Consultanță fiscală, contabilitate și salarizare', amount: 6083.33, currency: 'RON', spendDate: '2026-08-01', isRecurring: true, periodType: 'monthly', createdAt: '2026-08-25T00:00:00Z' },
  { id: 'sp_cnt_2', organizationId: DEMO_ORG.id, supplierId: 'sup_contaudit', supplierName: 'ContAudit & Tax Advisory', category: 'Servicii', description: 'Consultanță fiscală, contabilitate și salarizare', amount: 6083.33, currency: 'RON', spendDate: '2026-07-01', isRecurring: true, periodType: 'monthly', createdAt: '2026-07-25T00:00:00Z' },

  // Consumabile & Birotică: ~2.875 lei/month
  { id: 'sp_lyr_1', organizationId: DEMO_ORG.id, supplierId: 'sup_lyreco', supplierName: 'Lyreco România', category: 'Consumabile', description: 'Materiale ambalare colete & birotică birouri', amount: 2875.50, currency: 'RON', spendDate: '2026-08-01', isRecurring: true, periodType: 'monthly', createdAt: '2026-08-20T00:00:00Z' },
  { id: 'sp_lyr_2', organizationId: DEMO_ORG.id, supplierId: 'sup_lyreco', supplierName: 'Lyreco România', category: 'Consumabile', description: 'Materiale ambalare colete & birotică birouri', amount: 2790.00, currency: 'RON', spendDate: '2026-07-01', isRecurring: true, periodType: 'monthly', createdAt: '2026-07-20T00:00:00Z' },

  // Software (Google): ~2.200 lei/month
  { id: 'sp_ggl_1', organizationId: DEMO_ORG.id, supplierId: 'sup_google', supplierName: 'Google Ireland Ltd', category: 'Software', description: 'Google Workspace Enterprise 32 seats', amount: 2200.00, currency: 'RON', spendDate: '2026-08-01', isRecurring: true, periodType: 'monthly', createdAt: '2026-08-02T00:00:00Z' },
  { id: 'sp_ggl_2', organizationId: DEMO_ORG.id, supplierId: 'sup_google', supplierName: 'Google Ireland Ltd', category: 'Software', description: 'Google Workspace Enterprise 32 seats', amount: 2200.00, currency: 'RON', spendDate: '2026-07-01', isRecurring: true, periodType: 'monthly', createdAt: '2026-07-02T00:00:00Z' },

  // Telecom (Vodafone): ~1.533 lei/month
  { id: 'sp_vdf_1', organizationId: DEMO_ORG.id, supplierId: 'sup_vodafone', supplierName: 'Vodafone România SA', category: 'Telecom', description: 'Abonamente voce & date 24 SIM flotă', amount: 1533.33, currency: 'RON', spendDate: '2026-08-01', isRecurring: true, periodType: 'monthly', createdAt: '2026-08-15T00:00:00Z' },
  { id: 'sp_vdf_2', organizationId: DEMO_ORG.id, supplierId: 'sup_vodafone', supplierName: 'Vodafone România SA', category: 'Telecom', description: 'Abonamente voce & date 24 SIM flotă', amount: 1533.33, currency: 'RON', spendDate: '2026-07-01', isRecurring: true, periodType: 'monthly', createdAt: '2026-07-15T00:00:00Z' },
];

export const DEMO_BENCHMARKS: MarketBenchmark[] = [
  {
    id: 'bm_telco_sim',
    category: 'Telecom',
    serviceTier: 'B2B Voice & 50GB Data SIM',
    unitMetric: 'lei/SIM/lună',
    p25Price: 38.00,
    p50MedianPrice: 48.00,
    p75Price: 65.00,
    currency: 'RON',
    provenance: 'dataset_source',
    sampleSize: 142,
    updatedAt: '2026-07-01T00:00:00Z',
  },
  {
    id: 'bm_courier_awb',
    category: 'Curierat',
    serviceTier: 'Standard National Parcel (<3kg, 500+ AWB/mo)',
    unitMetric: 'lei/expediere',
    p25Price: 9.80,
    p50MedianPrice: 10.90,
    p75Price: 13.50,
    currency: 'RON',
    provenance: 'manually_verified',
    sampleSize: 88,
    updatedAt: '2026-07-15T00:00:00Z',
  },
  {
    id: 'bm_saas_productivity',
    category: 'Software',
    serviceTier: 'Enterprise Productivity Suite',
    unitMetric: 'lei/utilizator/lună',
    p25Price: 35.00,
    p50MedianPrice: 48.00,
    p75Price: 72.00,
    currency: 'RON',
    provenance: 'supplier_quote',
    sampleSize: 64,
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'bm_energy_mwh',
    category: 'Energie',
    serviceTier: 'Furnizare Energie Non-Casnic JT',
    unitMetric: 'lei/MWh',
    p25Price: 680.00,
    p50MedianPrice: 740.00,
    p75Price: 860.00,
    currency: 'RON',
    provenance: 'dataset_source',
    sampleSize: 210,
    updatedAt: '2026-08-10T00:00:00Z',
  },
];
