import { 
  VerifiedDemand, 
  DemandPool, 
  DemandPoolMember, 
  MarketplaceSupplier, 
  SupplierBid, 
  ClientOffer 
} from '../types';

export const DEMO_VERIFIED_DEMANDS: VerifiedDemand[] = [
  {
    id: 'vd_demo_telecom_01',
    organizationId: 'org_demo_01',
    organizationName: 'Nova Retail SRL',
    sourceContractId: 'ctr_vdf_01',
    category: 'Telecom',
    serviceType: 'Flotă SIM Voce & Date Mobile',
    incumbentSupplierId: 'sup_vodafone',
    incumbentSupplierName: 'Vodafone România SA',
    currentMonthlyCost: 1533,
    currentAnnualCost: 18400,
    volume: 24,
    unit: 'SIM',
    currentUnitPrice: 63.88,
    contractEndDate: '2026-11-30',
    noticeDeadline: '2026-10-31',
    eligibleFrom: '2026-08-01',
    confidenceScore: 95,
    status: 'pool_eligible',
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-08-15T10:00:00Z',
  },
  {
    id: 'vd_demo_curierat_02',
    organizationId: 'org_demo_01',
    organizationName: 'Nova Retail SRL',
    category: 'Curierat',
    serviceType: 'Expedieri Colete Național Standard',
    incumbentSupplierName: 'Fan Courier Express SRL',
    currentMonthlyCost: 3200,
    currentAnnualCost: 38400,
    volume: 180,
    unit: 'parcel',
    currentUnitPrice: 17.78,
    contractEndDate: '2026-12-31',
    noticeDeadline: '2026-11-30',
    eligibleFrom: '2026-08-10',
    confidenceScore: 90,
    status: 'pooled',
    createdAt: '2026-08-18T10:00:00Z',
    updatedAt: '2026-08-28T10:00:00Z',
  },
  {
    id: 'vd_demo_software_03',
    organizationId: 'org_demo_01',
    organizationName: 'Nova Retail SRL',
    category: 'Software',
    serviceType: 'Abonamente Software & Licențe Utilizator',
    incumbentSupplierName: 'Microsoft Cloud Ireland',
    currentMonthlyCost: 1450,
    currentAnnualCost: 17400,
    volume: 12,
    unit: 'seat',
    currentUnitPrice: 120.83,
    contractEndDate: '2026-10-15',
    noticeDeadline: '2026-09-15',
    eligibleFrom: '2026-08-01',
    confidenceScore: 92,
    status: 'offer_available',
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-08-30T10:00:00Z',
  },
];

export const DEMO_DEMAND_POOLS: DemandPool[] = [
  {
    id: 'pool_telecom_voice_data',
    category: 'Telecom',
    serviceType: 'Flotă SIM Voce & Date Mobile',
    title: 'Grup IMM: Flotă SIM-uri Mobile (Volum Cumulat 110+ abonamente)',
    region: 'Național',
    currency: 'RON',
    status: 'open_for_bids',
    totalCompanies: 8,
    totalVolume: 114,
    totalCurrentAnnualSpend: 78500,
    biddingStartsAt: '2026-08-25T08:00:00Z',
    biddingEndsAt: '2026-09-15T18:00:00Z',
    createdAt: '2026-08-20T10:00:00Z',
    updatedAt: '2026-08-30T10:00:00Z',
  },
  {
    id: 'pool_curierat_national',
    category: 'Curierat',
    serviceType: 'Expedieri Colete Național Standard',
    title: 'Grup IMM: Expedieri Colete Naționale (Volum Cumulat 3.200 colete/lună)',
    region: 'Național',
    currency: 'RON',
    status: 'open_for_bids',
    totalCompanies: 14,
    totalVolume: 3200,
    totalCurrentAnnualSpend: 480000,
    biddingStartsAt: '2026-08-28T08:00:00Z',
    biddingEndsAt: '2026-09-20T18:00:00Z',
    createdAt: '2026-08-22T10:00:00Z',
    updatedAt: '2026-08-31T10:00:00Z',
  },
  {
    id: 'pool_software_workspace',
    category: 'Software',
    serviceType: 'Abonamente Software & Licențe Utilizator',
    title: 'Grup IMM: Suită Productivitate Cloud & Securitate',
    region: 'Național',
    currency: 'RON',
    status: 'offers_ready',
    totalCompanies: 5,
    totalVolume: 65,
    totalCurrentAnnualSpend: 54000,
    biddingStartsAt: '2026-08-15T08:00:00Z',
    biddingEndsAt: '2026-08-30T18:00:00Z',
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-08-31T10:00:00Z',
  },
];

export const DEMO_DEMAND_POOL_MEMBERS: DemandPoolMember[] = [
  {
    id: 'dpm_01',
    demandPoolId: 'pool_curierat_national',
    verifiedDemandId: 'vd_demo_curierat_02',
    organizationId: 'org_demo_01',
    organizationName: 'Nova Retail SRL',
    consentStatus: 'accepted',
    joinedAt: '2026-08-28T11:00:00Z',
  },
  {
    id: 'dpm_02',
    demandPoolId: 'pool_software_workspace',
    verifiedDemandId: 'vd_demo_software_03',
    organizationId: 'org_demo_01',
    organizationName: 'Nova Retail SRL',
    consentStatus: 'accepted',
    joinedAt: '2026-08-15T14:30:00Z',
  },
];

export const DEMO_MARKETPLACE_SUPPLIERS: MarketplaceSupplier[] = [
  {
    id: 'mkt_sup_orange',
    companyName: 'Orange România Communications SA',
    cui: 'RO1015322',
    website: 'https://orange.ro/business',
    categories: ['Telecom'],
    contactEmail: 'b2b-licitatii@orange.ro',
    verified: true,
    status: 'active',
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'mkt_sup_dpd',
    companyName: 'DPD România (Dynamic Parcel Distribution SA)',
    cui: 'RO13524678',
    website: 'https://dpd.ro',
    categories: ['Curierat'],
    contactEmail: 'oferte-b2b@dpd.ro',
    verified: true,
    status: 'active',
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'mkt_sup_connections',
    companyName: 'Connections Consult SA (Cloud Solutions)',
    cui: 'RO17711425',
    website: 'https://connectionsconsult.ro',
    categories: ['Software'],
    contactEmail: 'licitatii@connectionsconsult.ro',
    verified: true,
    status: 'active',
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
];

export const DEMO_SUPPLIER_BIDS: SupplierBid[] = [
  {
    id: 'bid_orange_01',
    demandPoolId: 'pool_telecom_voice_data',
    marketplaceSupplierId: 'mkt_sup_orange',
    marketplaceSupplierName: 'Orange România Communications SA',
    pricingModel: 'unit_fixed',
    pricePerUnit: 38.50, // 38.50 lei / SIM
    estimatedMonthlyTotal: 4389,
    estimatedAnnualTotal: 52668,
    contractDurationMonths: 24,
    minimumVolume: 100,
    slaSummary: 'Disponibilitate rețea 99.9%, suport tehnic prioritar 24/7 dedicat IMM.',
    benefits: ['100GB trafic 5G inclus', 'Roaming SEE complet', 'Înlocuire SIM în 4h'],
    conditions: 'Valabil la semnarea contractului colectiv pentru minim 100 SIM-uri.',
    validUntil: '2026-09-30',
    status: 'submitted',
    createdAt: '2026-08-29T14:00:00Z',
    updatedAt: '2026-08-29T14:00:00Z',
  },
  {
    id: 'bid_dpd_01',
    demandPoolId: 'pool_curierat_national',
    marketplaceSupplierId: 'mkt_sup_dpd',
    marketplaceSupplierName: 'DPD România',
    pricingModel: 'unit_fixed',
    pricePerUnit: 12.80, // 12.80 lei / colet
    estimatedMonthlyTotal: 40960,
    estimatedAnnualTotal: 491520,
    contractDurationMonths: 24,
    minimumVolume: 2500,
    slaSummary: 'Livrare 24-48h național, integrare automată API cu magazinul online.',
    benefits: ['Ramburs în cont colector gratuit', '0 km suplimentari', 'Asigurare inclusă până la 1000 lei'],
    conditions: 'Tarif garantat pentru volumul agregat de 3.000+ colete/lună.',
    validUntil: '2026-09-25',
    status: 'shortlisted',
    createdAt: '2026-08-30T10:00:00Z',
    updatedAt: '2026-08-30T10:00:00Z',
  },
  {
    id: 'bid_connections_01',
    demandPoolId: 'pool_software_workspace',
    marketplaceSupplierId: 'mkt_sup_connections',
    marketplaceSupplierName: 'Connections Consult SA',
    pricingModel: 'unit_fixed',
    pricePerUnit: 95.00, // 95 lei / seat
    estimatedMonthlyTotal: 6175,
    estimatedAnnualTotal: 74100,
    contractDurationMonths: 24,
    minimumVolume: 50,
    slaSummary: 'Certificare Microsoft Tier 1 Cloud Solutions Provider, migrare asistată.',
    benefits: ['Securitate Defender for Business', '1TB cloud storage/user', 'Migrare gratuită date'],
    conditions: 'Preț blocat în lei pe 24 luni, fără indexare automată de inflație.',
    validUntil: '2026-09-15',
    status: 'selected',
    createdAt: '2026-08-28T09:00:00Z',
    updatedAt: '2026-08-31T12:00:00Z',
  },
];

export const DEMO_CLIENT_OFFERS: ClientOffer[] = [
  {
    id: 'offer_demo_software_01',
    organizationId: 'org_demo_01',
    verifiedDemandId: 'vd_demo_software_03',
    demandPoolId: 'pool_software_workspace',
    supplierBidId: 'bid_connections_01',
    supplierName: 'Connections Consult SA (Partener Gold)',
    currentAnnualCost: 17400,
    proposedAnnualCost: 13680,
    estimatedSavings: 3720,
    savingsPercentage: 21.38,
    proposedUnitPrice: 95.00,
    unit: 'seat',
    volume: 12,
    contractDurationMonths: 24,
    summary: 'Ofertă colectivă obținută prin Demand Pool Software. Prețul pe utilizator scade de la 120,83 lei la 95 lei/lună garantat pe 24 de luni, cu migrare gratuită inclusă.',
    validUntil: '2026-09-20',
    status: 'offered',
    createdAt: '2026-08-31T15:00:00Z',
  },
];
